### ISSUE TITLE
Decide if we get enough value from c++ symbols tracking to keep doing it

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu-mir#26]
seb128 has raised the question of symbols tracking:

https://lists.ubuntu.com/archives/ubuntu-devel/2023-June/042600.html

I don't know what value we get from this, and if we get enough value to justify maintaining it.

**Comment by cpaelzer** [comment]
This was discussed, and decided to be worth having a look, but not worth insisting on it.
PR #27 clarified the ruling so that reviews can easily consider this special path for C++ symbols tracking.
