### ISSUE TITLE
Should we ask for a bit of research/investment on isolation?

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-mir#34]
Hi,
Server team has usually tried (but not always succeeded) to use isolation features.
Historically that has been mostly apparmor but right now we have the benefit of [Debian also caring for it from the systemd side](https://wiki.debian.org/ReleaseGoals/SystemdAnalyzeSecurity).

IMHO we do not want to `require` those, but asking/recommending it - sometimes in contrast to what a service does (e.g. more useful on high exposure) it might be very useful.

This issue shall start an open discussion to check how everyone feels about this.

In my humble and simplified opinion it could be "whenever we say, this needs security" we should also say "please have a look at providing an apparmor profile and/or improve the usage of systemd isolation features".

WDYT?

**Comment by slyon** [comment]
I've been recommending systemd isolation features in some of my reviews, especially if there's already a systemd service unit in place. I'm not very used to apparmor, but I think it'd make sense to have a checklist item to remind us of those checks.

+1

**Comment by setharnold** [comment]
I'm broadly supportive of this, especially systemd's seccomp filters. The various `ProtectSystem` and `ProtectHome` style options introduce namespacing that might be surprising to users or complicate AppArmor profiles (and I'm not sure how well they'd work in nested containers) -- so it's not an obvious case of "turn on everything" but certainly we can be doing more.
