### ISSUE TITLE
Externally created branch

### ISSUE THREAD

**Issue by dviererbe** [canonical/ubuntu-mir#38]
AFAICT there is a [`renovate/configure` branch](https://github.com/canonical/ubuntu-mir/tree/renovate/configure) in this Repo from PR #25

The weird thing is that this was a marketing PR by an external actor. How could they create a new branch in this Repository? They shouldn't have the permission for that.

I only noticed it, because the [`ubuntu-packaging-guide` Repo](https://github.com/canonical/ubuntu-packaging-guide) also had such a PR and such a branch.

**Comment by cpaelzer** [comment]
This is handled by now, thanks for bringing it up.

**Comment by setharnold** [comment]
One of the security team's private github trees also got such a branch, which was surprising, but I heard second-hand that Joao said it's fine to use it. (Here's wishing we had something a bit more formal.)

**Comment by eslerm** [comment]
João directed me to Seager. *We* decided not to worry about this, since nothing confidential is hosted on GitHub where the bots have access.
