### ISSUE TITLE
deprecated crypto defaults

### ISSUE THREAD

**Issue by eslerm** [canonical/ubuntu-mir#44]
I am unsure if this issue belongs here or just as a note for Security reviewers in https://git.launchpad.net/ubuntu-security-tools/tree/audits/workflow.template#n219

Spec FO152 (pending) aims to disable TLS 1.0 and 1.1 by default, as these were deprecated by RFC 8996 in 2021. If a MIR package uses TLS/SSL the owning team should be responsible for spec compliance.

**Comment by adrien-n** [comment]
I typically use sslscan to assess which protocols and ciphers are enabled. Its colored output is not normed but is a good start if you don't know what you're looking at. :) 
Just follow the packages' docs on how to enable TLS and use the "snakeoil" certs generated by the "ssl-cert" package.

Example (you can try "sslscan example.com" for a different output):

    % sslscan ubuntu.com
    Version: 2.0.16-12-g547296f-wip
    OpenSSL 3.0.10 1 Aug 2023

    Connected to 185.125.190.20

    Testing SSL server ubuntu.com on port 443 using SNI name ubuntu.com

      SSL/TLS Protocols:
    SSLv2     disabled
    SSLv3     disabled
    TLSv1.0   disabled
    TLSv1.1   disabled
    TLSv1.2   enabled
    TLSv1.3   enabled

      TLS Fallback SCSV:
    Server supports TLS Fallback SCSV

      TLS renegotiation:
    Session renegotiation not supported

      TLS Compression:
    OpenSSL version does not support compression
    Rebuild with zlib1g-dev package for zlib support

      Heartbleed:
    TLSv1.3 not vulnerable to heartbleed
    TLSv1.2 not vulnerable to heartbleed

      Supported Server Cipher(s):
    Preferred TLSv1.3  256 bits  TLS_AES_256_GCM_SHA384        Curve 25519 DHE 253
    Accepted  TLSv1.3  256 bits  TLS_CHACHA20_POLY1305_SHA256  Curve 25519 DHE 253
    Accepted  TLSv1.3  128 bits  TLS_AES_128_GCM_SHA256        Curve 25519 DHE 253
    Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve 25519 DHE 253
    Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
    Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve 25519 DHE 253
    Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve 25519 DHE 253

      Server Key Exchange Group(s):
    TLSv1.3  128 bits  secp256r1 (NIST P-256)
    TLSv1.3  192 bits  secp384r1 (NIST P-384)
    TLSv1.3  260 bits  secp521r1 (NIST P-521)
    TLSv1.3  128 bits  x25519
    TLSv1.3  224 bits  x448
    TLSv1.2  128 bits  secp256r1 (NIST P-256)
    TLSv1.2  192 bits  secp384r1 (NIST P-384)
    TLSv1.2  260 bits  secp521r1 (NIST P-521)
    TLSv1.2  128 bits  x25519
    TLSv1.2  224 bits  x448

      SSL Certificate:
    Signature Algorithm: sha256WithRSAEncryption
    RSA Key Strength:    2048

    Subject:  ubuntu.com
    Altnames: DNS:ubuntu.com, DNS:www.ubuntu.com
    Issuer:   R3

    Not valid before: Jan  1 08:28:56 2024 GMT

Of course, with a snakeoil cert, the SSL certificate won't be considered valid.

**Comment by cpaelzer** [comment]
I feel we should place a hint that this is expected in the submitters template (for awareness) but the check would IMHO live best in the note for Security reviewers that @eslerm mentioned.

Let us discuss and conclude the way forward in the next MIR team meeting.

**Comment by eslerm** [comment]
Thanks @cpaelzer. A light hint so that owning teams expect sounds perfect. Is that hint okay as a soft check?  https://github.com/canonical/ubuntu-mir/pull/45

A more in-depth check will be performed by the Security team.
