### ISSUE TITLE
cargo vendor adds unnecessary crates

### ISSUE THREAD

**Issue by eslerm** [canonical/ubuntu-mir#51]
`cargo vendor` adds unnecessary crates (like windows specific crates) which is impacting [MIRs](https://bugs.launchpad.net/ubuntu/+source/authd/+bug/2048781). This adds bandiwidth/resource and maintenance cost. Previously this has been discussed on https://github.com/rust-lang/cargo/issues/11929 and https://github.com/canonical/ubuntu-mir/issues/35#issuecomment-1859325671. A fix is out of scope for upstream.

This was brought up at the weekly MIR meeting:
```
slyon> Yes, I think it's manual work. The package should have some script to drop unneeded stuff and mangle the manifest accordingly
[...]
slyon> I think longer term we'd need upstream toolchain support to vendor only the necessary deps
slyon> but that's not something that we have right now.
[...]
didrocks> yeah, I think that should be done centrally, at worst, in the packaging tooling then
didrocks> otherwise, everyone will have different ways of doing it, hard to update and so on
slyon> I can put it into the Foundations/Toolchain squad's backlog for review during next roadmap planning
```

Thanks for adding [FR-6859](https://warthogs.atlassian.net/browse/FR-6859) @slyon. @didrocks 

What is the short term solution? We likely ignore this case for Go packages already. I'm okay with ignoring crates if a planned fix has a solid release cycle.

[FR-6859]: https://warthogs.atlassian.net/browse/FR-6859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by didrocks** [comment]
I can’t commit for the foundation team, but to me, we should ignore it for now (it’s not the first package in the distro suffering from this from what I saw). Then, let’s ensure this is correctly planned on the foundation toolchain team backlog as they have full time maintainers for each languages, responsible for the debhelper part.

That way, we ensure we don’t add technical debts to our existing packages, and that their next rebuild will follow our default trimming policy without discrepancies between sources.

Does it make sense?

**Comment by cpaelzer** [comment]
```
[16:52] <cpaelzer> so what can we do for now, other than expecting anyone touching it to manually do the culling to those that matters?
[16:52] <sarnold> should we ask for those to be deleted by hand before release? shipping that to all mirrors for ten more years makes me sad :(
[16:52] <cpaelzer> we can not say "no rust until it solved" not can we "all that is listed needs to be fully reviewed" :-/
[16:53] <cpaelzer> sarnold: with "by hand" you mean d/rules removing them along the source build and build?
[16:53] <sarnold> cpaelzer: exactly
```

**Comment by didrocks** [comment]
@cpaelzer I don’t see that happening if we want to do the correct job for this cycle, with analyzing dependencies and so on. We already contributed quite a lot to vendoring which was not working in Rust in the previous cycles, I don’t realistically see us taking that load this cycles with all the other extra requirements that arrived upon us with the current staffing. I think until the toolchain team can provide a generic solution, our package will remain in universe then.

**Comment by eslerm** [comment]
Packages like `authd` are certainly valuable in main.

A completely thorough job of removing unnecessary crates is an unreasonable ask. This is an especially onerous ask for Rust is especially unreasonable, since this requirement is currently not being applied to Go.

@didrocks would a best effort removal be acceptable until toolchains can delivery a solution? Perhaps just the Windows specific crates and any additional crates that are flagged in bug reports?

**Comment by didrocks** [comment]
If the security team is fine with only removing the _win ones, I’m happy to add that to our packaging and ensuring with CI it’s still building. Then, anything else which is pulled and flagged as such can be marked for removal too. We need to experiment then that cargo doesn’t resolve the dependency and complain about it, but it sounds like this would be achievable!

**Comment by eslerm** [comment]
That sounds reasonable to me :)

I don't believe this issue was a Security team concern.

**Comment by slyon** [comment]
Consensus here is to drop unnecessary crates on a "best effort" basis, while waiting for Foundation's toolchain squad to come up with a centralized & automated solution.

E.g.: https://gitlab.gnome.org/GNOME/snapshot/-/issues/137
