### ISSUE TITLE
Remove libgoa from the upstream redflags

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-mir#54]
The upstream redflags section currently includes

> TODO: - no dependency on webkit, qtwebkit, seed or libgoa-*

libgoa being a red flag came recently as a discussion point in the msgraph MIR, https://bugs.launchpad.net/ubuntu/+source/msgraph/+bug/2060035

Checking the history libgoa was added at the same time as the section it's in (https://wiki.ubuntu.com/MainInclusionProcess/?action=diff&rev2=32&rev1=31). I'm assuming the reason it was added it because it was depending on webkitgtk. 

gnome-online-accounts upstream removed the depends on webkitgtk in favor of just calling to the standard browser for oauth2 authentication, the change is in the Noble version of libgoa
https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/merge_requests/139

If libgoa isn't using webkitgtk anymore could it be removed from the list of redflags?

**Comment by slyon** [comment]
+1 for dropping the "no-runtime-dependeny on `libgoa-*`" requirement. It doesn't make sense anymore.

**Comment by cpaelzer** [comment]
Discussed in MIR meeting, agreed - will be dropped.
