### ISSUE TITLE
Flowchart seems a bit broken

### ISSUE THREAD

**Issue by setharnold** [canonical/ubuntu-mir#67]
Hello, the flowchart seems to be missing some contents, four of the boxes don't show any contents for me:

![2024-09-16_22-55](https://github.com/user-attachments/assets/68aee4f5-67e9-4b76-89a2-debf703b07bc)

Thanks

**Comment by slyon** [comment]
Strange, it seems to be working for me. One obvious difference is that I'm not using a dark theme, not sure if that could be related.

@dviererbe Do you have any insights into that?

**Comment by slyon** [comment]
fixed in https://github.com/canonical/ubuntu-mir/issues/67
