### ISSUE TITLE
Do we benefit from having the dev binary packages promoted?

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-mir#69]
I'm opening one to start a follow discussion to the 0. review comment on https://bugs.launchpad.net/bugs/2080965

> #0 - This is mostly a build-time helper tool, do we really need it in main, or should we consider demoting reverse-depends (like libglib2.0-dev) to universe instead?

Demoting libglib2.0-dev isn't easy because it's a low level libraries that most other desktop dev libraries depends on. We regularly have issues with dev packages and end up demoting and excluding some of those. Which makes me wonder, why do we default to promote those? Should we reconsider that position?

**Comment by slyon** [comment]
By default, we promote packages on a source package level, only excluding specific binaries (such as `*-dev` packages) as needed. Also, we do not generally require `Build-Depends` to be in "main", only runtime depends.

The important exception here is for build-time tooling that affects the resulting binaries (e.g. compilers), and other critical infrastructure that we depend on in our daily work as Ubuntu developers.

During MIR review we already watch out for cases where we'd want to exclude -dev packages, if they are not strictly necessary and bring unnecessary extra work (e.g. pulling fonts packages into main from a -doc package). The [template](https://github.com/canonical/ubuntu-mir#reviewing-a-bug) reads:

```
- no -dev/-debug/-doc packages that need exclusion
```

**Comment by slyon** [comment]
@jbicha says "https://git.launchpad.net/~ubuntu-core-dev/ubuntu-seeds/+git/ubuntu/commit/?id=4c41750b is an approximation of the number of excludes you would need"

**Comment by cpaelzer** [comment]
Nothing more came up and the position still is what we feel to be the right approach (handle all the same).
Closing for now as part of the MIR sync.
